useGroupedVersion: true

version_info_list_mobile:
  - value: 9.x
    child:
      - 9.6.40_reactNative
      - 9.6.40_xamarin
      - 9.6.40_cordova
      - 9.6.40_flutter
      - 9.6.40_android
      - 9.6.40_iOS
      - 9.6.20_android
      - 9.6.11_android
      - 9.6.10_android
      - 9.6.0_android
      - 9.4.0_android
      - 9.2.11_android
      - 9.2.10_android
      - 9.0.2_android
      - 9.0.1_android
      - 9.0.0_android
      - 9.6.40_ios
      - 9.6.20_ios
      - 9.6.10_ios
      - 9.6.0_ios
      - 9.4.0_ios
      - 9.2.13_ios
      - 9.2.10_ios
      - 9.0.2_ios
      - 9.0.1_ios
      - 9.0.0_ios
  - value: 8.x
    child:
      - 8.9.3_android
      - 8.9.1_android
      - 8.9.0_android
      - 8.8.0_android
      - 8.6.0_android
      - 8.4.0_android
      - 8.2.1_android
      - 8.2.0_android
      - 8.1.2_android
      - 8.1.0_android
      - 8.0.0_android
      - 8.9.3_ios
      - 8.9.1_ios
      - 8.9.0_ios
      - 8.8.0_ios
      - 8.6.0_ios
      - 8.4.0_ios
      - 8.2.1_ios
      - 8.2.0_ios
      - 8.1.2_ios
      - 8.1.0_ios
      - 8.0.0_ios
  - value: 7.x
    child:
      - 7.6.0_android
      - 7.5.0_android
      - 7.6.0_ios
      - 7.5.0_ios